Ensure all task exceptions are handled, to prevent crashes.
Abedalkareem/games_services pull request #138
Opened 2024-01-02 14:54 UTC by Erfa

`task.result.get()` crashes for me when calling `loadAchievement` in one scenario. I don't think this is intentional? Seems like this should be handled by the failure listener which was already present. After this change it is.

I also changed a similar case with leaderboards and saves. After this no completeListeners should assume that data exists.

Disclaimer: I don't really know Kotlin and haven't worked with native Android in years, but it seems pretty straightforward.

2024-01-04 20:03 UTC, theLee3 commented
This solves crash from #133.

We still need to call follow the instructions [here](https://developers.google.com/android/reference/com/google/android/gms/games/FriendsResolutionRequiredException) to acquire the permission to load friendsOnly leaderboards.

2024-01-04 20:04 UTC, theLee3 commented
Out of curiosity @Erfa, what one scenario led to the crash when calling `loadAchievement`?

2024-01-07 13:17 UTC, Erfa commented
> Out of curiosity @Erfa, what one scenario led to the crash when calling `loadAchievement`?

I was running it on an emulator which I had apparently loaded with an image that didn't have Play Store support. Reproducible every time for me.

2024-01-08 03:40 UTC, Abedalkareem approved these changes

2024-01-08 19:04 UTC, theLee3 commented
@Abedalkareem  I will have the permission request sorted within a couple of days.

2024-01-25 18:24 UTC, theLee3 requested changes
Please remove your changes to `Leaderboards.kt` from this PR as a more extensive fix had to be merged to account for a permission request.

2024-01-28 10:27 UTC, Erfa commented
Something like that?

2024-01-29 17:39 UTC, theLee3 commented
Perfect. Thanks @Erfa.

2024-01-29 17:39 UTC, theLee3 approved these changes

2024-01-29 18:03 UTC, merged