Updated play-services-games to fix NPE
Abedalkareem/games_services pull request #55
Opened 2022-01-26 01:18 UTC by impure

The old version had a null pointer exception as mentioned here: https://developers.google.com/android/guides/releases#december_16_2021

2022-01-26 08:46 UTC, gyuri-fluttech commented
Thanks @impure , I think this is the way we should go.

2022-01-26 09:41 UTC, jonafeucht requested changes
G2K that it isn't a problem with the package.
I think it would be best to also update play-services-auth to 20.0.1

2022-01-27 15:41 UTC, impure commented
OK, I also updated play-services-auth.

2022-01-28 02:56 UTC, Abedalkareem approved these changes

2022-01-28 02:56 UTC, Abedalkareem commented
Thanks for the fix!

2022-01-28 02:56 UTC, merged